theme: jekyll-theme-minimal
title: Ryan Voyack
author: Ryan Voyack
logo: headshot.png
description: Projects spanning my work as a data scientist and actuary in the insurance industry, personal projects, mathematics.
