theme: jekyll-theme-minimal
title: My Portfolio
author: Ryan Voyack
image: headshot.png
description: Projects spanning my work as a data scientist and actuary in the insurance industry, personal projects, mathematics.
